services:
  ros2_experiment:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2_experiment
    ports:
      - 50002:50002
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROBOT_IP=${ROBOT_IP:-192.168.1.20}  # Default IP for real robot, override with environment
    volumes:
      - ./src:/ros2_ws/src/my_packages
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:ro
      - /dev/:/dev/
    network_mode: host
    privileged: true
    tty: true